[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/custom-addons,/mnt/extra-addons
data_dir = /var/lib/odoo
debug_assets = True

# DB
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

# Workers + WebSocket
workers = 2
max_cron_threads = 1
proxy_mode = True
gevent_port = 8072
server_wide_modules = web,bus

# Optional
logfile = /var/log/odoo/odoo.log
